
FUNCS_FROM_CHAINRULES = [
    :(Base.FastMath.mul_fast),
    :(Base.FastMath.sincos_fast),
    :(Base.FastMath.log10_fast),
    :(Base.FastMath.rem_fast),
    :(Base.FastMath.sqrt_fast),
    :(Base.FastMath.abs_fast),
    :(Base.FastMath.div_fast),
    :(Base.FastMath.conj_fast),
    :(Base.FastMath.exp_fast),
    :(Base.FastMath.cbrt_fast),
    :(Base.FastMath.sign_fast),
    :(Base.FastMath.angle_fast),
    :(Base.FastMath.atan_fast),
    :(Base.FastMath.sin_fast),
    :(Base.FastMath.tan_fast),
    :(Base.FastMath.exp2_fast),
    :(Base.FastMath.min_fast),
    :(Base.FastMath.sinh_fast),
    :(Base.FastMath.log2_fast),
    :(Base.FastMath.log1p_fast),
    :(Base.FastMath.abs2_fast),
    :(Base.FastMath.cosh_fast),
    :(Base.FastMath.log_fast),
    :(Base.FastMath.exp10_fast),
    :(Base.FastMath.tanh_fast),
    :(Base.FastMath.sub_fast),
    :(Base.FastMath.hypot_fast),
    :(Base.FastMath.add_fast),
    :(Base.FastMath.cos_fast),
    :(Base.FastMath.expm1_fast),
    :(Base.FastMath.acos_fast),
    :(Base.FastMath.asin_fast),
    :(Base.FastMath.pow_fast),
    :(Base.FastMath.max_fast),
    :(Base.FastMath.inv_fast),
]

for func in FUNCS_FROM_CHAINRULES
    @eval @grad_from_cr $func
end
