name: format-check

on:
  push:
    branches:
      - 'master'
    tags: '*'
  pull_request:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
        matrix:
          version:
            - '1.9'
          os:
            - ubuntu-latest
          arch:
            - x64
    steps:
      - uses: actions/checkout@v4
      - uses: julia-actions/setup-julia@v1
        with:
          version: ${{ matrix.version }}
          arch: ${{ matrix.arch }}
      - name: Install JuliaFormatter.jl
        run: julia  -e 'using Pkg; Pkg.add(PackageSpec(name="JuliaFormatter"))'
      - name: Format code
        run: julia  -e 'using JuliaFormatter; format(".", verbose=true)'
      - name: Format check
        run: |
          julia -e '
          out = Cmd(`git diff --name-only`) |> read |> String
          if out == ""
              exit(0)
          else
              @error "Some files have not been formatted !!!"
              write(stdout, out)
              exit(1)
          end'
